function state_derivative = dc_motor_ode( ...
        ~, state, applied_voltage, motor_parameters)
%DC_MOTOR_ODE Calculate the state derivatives of a DC motor.
%
% State variables:
%   state(1) = armature current [A]
%   state(2) = angular velocity [rad/s]

    armature_current = state(1);
    angular_velocity = state(2);

    armature_current_derivative = ( ...
        applied_voltage ...
        - motor_parameters.armature_resistance * armature_current ...
        - motor_parameters.back_emf_constant * angular_velocity ...
    ) / motor_parameters.armature_inductance;

    angular_velocity_derivative = ( ...
        motor_parameters.torque_constant * armature_current ...
        - motor_parameters.viscous_damping * angular_velocity ...
        - motor_parameters.load_torque ...
    ) / motor_parameters.rotor_inertia;

    state_derivative = [
        armature_current_derivative;
        angular_velocity_derivative
    ];
end