%% ES 3011 - Lab 2
% Modeling and Simulation of a DC Motor
%
% This script compares the time-domain ODE model with the
% corresponding transfer-function model you'll have to mess with the time
% to make it look like the one in the lab but should be fine - jefferson

clear;
clc;
close all;


%% Motor parameters

motor_parameters.armature_resistance = 0.5;       % [ohm]
motor_parameters.armature_inductance = 0.002;     % [H]

motor_parameters.back_emf_constant = 0.05;        % [V*s/rad]
motor_parameters.torque_constant = 0.05;          % [N*m/A]

motor_parameters.viscous_damping = 0.0004;        % [N*m*s/rad]
motor_parameters.rotor_inertia = 0.00009;         % [kg*m^2]
motor_parameters.load_torque = 0;                 % [N*m]


%% Simulation settings

applied_voltage = 10;                             % [V]

start_time = 0;                                   % [s]
end_time = 0.07;                                  % [s]
number_of_points = 1000;

simulation_time = linspace( ...
    start_time, ...
    end_time, ...
    number_of_points ...
).';

initial_armature_current = 0;                     % [A]
initial_angular_velocity = 0;                     % [rad/s]

initial_state = [
    initial_armature_current;
    initial_angular_velocity
];


%% Model coefficients

second_order_coefficient = ( ...
    motor_parameters.armature_inductance ...
    * motor_parameters.rotor_inertia ...
);

first_order_coefficient = ( ...
    motor_parameters.armature_inductance ...
    * motor_parameters.viscous_damping ...
) + ( ...
    motor_parameters.armature_resistance ...
    * motor_parameters.rotor_inertia ...
);

constant_coefficient = ( ...
    motor_parameters.armature_resistance ...
    * motor_parameters.viscous_damping ...
) + ( ...
    motor_parameters.back_emf_constant ...
    * motor_parameters.torque_constant ...
);

steady_state_denominator = constant_coefficient;


%% Part A - Time-domain simulation

[
    time_ode, ...
    armature_current, ...
    angular_velocity ...
] = simulate_dc_motor( ...
    simulation_time, ...
    initial_state, ...
    applied_voltage, ...
    motor_parameters ...
);


%% Figure 1 - Armature current

figure;

plot( ...
    time_ode, ...
    armature_current, ...
    'LineWidth', ...
    1.5 ...
);

xlabel('Time (s)');
ylabel('Armature Current, i_a (A)');
title('Armature Current vs. Time');

grid on;


%% Figure 2 - Angular velocity

figure;

plot( ...
    time_ode, ...
    angular_velocity, ...
    'LineWidth', ...
    1.5 ...
);

xlabel('Time (s)');
ylabel('Angular Velocity, \omega (rad/s)');
title('Angular Velocity vs. Time');

grid on;


%% Part B - Applied-voltage comparison

applied_voltages = [
    5;
    10;
    15
];

number_of_voltages = numel(applied_voltages);

armature_current_by_voltage = zeros( ...
    number_of_points, ...
    number_of_voltages ...
);

angular_velocity_by_voltage = zeros( ...
    number_of_points, ...
    number_of_voltages ...
);

steady_state_velocities = zeros( ...
    number_of_voltages, ...
    1 ...
);

steady_state_currents = zeros( ...
    number_of_voltages, ...
    1 ...
);

for voltage_index = 1:number_of_voltages

    current_voltage = applied_voltages(voltage_index);

    [
        ~, ...
        current_response, ...
        velocity_response ...
    ] = simulate_dc_motor( ...
        simulation_time, ...
        initial_state, ...
        current_voltage, ...
        motor_parameters ...
    );

    armature_current_by_voltage(:, voltage_index) = ...
        current_response;

    angular_velocity_by_voltage(:, voltage_index) = ...
        velocity_response;

    steady_state_velocities(voltage_index) = ( ...
        motor_parameters.torque_constant ...
        * current_voltage ...
    ) / steady_state_denominator;

    steady_state_currents(voltage_index) = ( ...
        motor_parameters.viscous_damping ...
        * steady_state_velocities(voltage_index) ...
    ) / motor_parameters.torque_constant;
end


%% Figure 3 - Angular velocity for different voltages

figure;
hold on;

for voltage_index = 1:number_of_voltages

    current_voltage = applied_voltages(voltage_index);

    plot( ...
        simulation_time, ...
        angular_velocity_by_voltage(:, voltage_index), ...
        'LineWidth', ...
        1.5, ...
        'DisplayName', ...
        sprintf('%g V', current_voltage) ...
    );
end

xlabel('Time (s)');
ylabel('Angular Velocity, \omega (rad/s)');
title('Angular Velocity for Different Applied Voltages');

legend('Location', 'best');

grid on;
hold off;


%% Figure 4 - Armature current for different voltages

figure;
hold on;

for voltage_index = 1:number_of_voltages

    current_voltage = applied_voltages(voltage_index);

    plot( ...
        simulation_time, ...
        armature_current_by_voltage(:, voltage_index), ...
        'LineWidth', ...
        1.5, ...
        'DisplayName', ...
        sprintf('%g V', current_voltage) ...
    );
end

xlabel('Time (s)');
ylabel('Armature Current, i_a (A)');
title('Armature Current for Different Applied Voltages');

legend('Location', 'best');

grid on;
hold off;


%% Part C - Transfer-function model

transfer_function_numerator = ...
    motor_parameters.torque_constant;

transfer_function_denominator = [
    second_order_coefficient, ...
    first_order_coefficient, ...
    constant_coefficient
];

motor_transfer_function = tf( ...
    transfer_function_numerator, ...
    transfer_function_denominator ...
);


%% Part C - Transfer-function simulation

voltage_input = applied_voltage ...
    * ones(size(simulation_time));

angular_velocity_tf = lsim( ...
    motor_transfer_function, ...
    voltage_input, ...
    simulation_time ...
);


%% Figure 5 - Transfer-function response

figure;

plot( ...
    simulation_time, ...
    angular_velocity_tf, ...
    'LineWidth', ...
    1.5 ...
);

xlabel('Time (s)');
ylabel('Angular Velocity, \omega (rad/s)');
title('Transfer-Function Motor Response');

grid on;


%% Part D - Compare ODE and transfer-function models

model_error = abs( ...
    angular_velocity ...
    - angular_velocity_tf ...
);

maximum_model_error = max(model_error);


%% Figure 6 - ODE and transfer-function comparison

figure;

plot( ...
    time_ode, ...
    angular_velocity, ...
    'LineWidth', ...
    1.5, ...
    'DisplayName', ...
    'ODE45 Model' ...
);

hold on;

plot( ...
    simulation_time, ...
    angular_velocity_tf, ...
    '--', ...
    'LineWidth', ...
    1.5, ...
    'DisplayName', ...
    'Transfer-Function Model' ...
);

xlabel('Time (s)');
ylabel('Angular Velocity, \omega (rad/s)');
title('ODE and Transfer-Function Comparison');

legend('Location', 'best');

grid on;
hold off;


%% Part E - Analytical steady-state values

steady_state_angular_velocity = ( ...
    motor_parameters.torque_constant ...
    * applied_voltage ...
) / steady_state_denominator;

steady_state_armature_current = ( ...
    motor_parameters.viscous_damping ...
    * steady_state_angular_velocity ...
) / motor_parameters.torque_constant;


%% Part E - Simulation performance values

[
    peak_armature_current, ...
    peak_current_index ...
] = max(armature_current);

peak_current_time = time_ode(peak_current_index);

final_angular_velocity = angular_velocity(end);
final_armature_current = armature_current(end);


%% Part E - Create numerical results tables

result_names = {
    'Applied Voltage';
    'Peak Armature Current';
    'Time of Peak Current';
    'Final Angular Velocity';
    'Final Armature Current';
    'Theoretical Steady-State Velocity';
    'Theoretical Steady-State Current';
    'Maximum ODE/TF Error'
};

result_values = [
    applied_voltage;
    peak_armature_current;
    peak_current_time;
    final_angular_velocity;
    final_armature_current;
    steady_state_angular_velocity;
    steady_state_armature_current;
    maximum_model_error
];

result_units = {
    'V';
    'A';
    's';
    'rad/s';
    'A';
    'rad/s';
    'A';
    'rad/s'
};

results_table = table( ...
    result_names, ...
    result_values, ...
    result_units, ...
    'VariableNames', ...
    {'Quantity', 'Value', 'Unit'} ...
);

voltage_results_table = table( ...
    applied_voltages, ...
    steady_state_velocities, ...
    steady_state_currents, ...
    'VariableNames', ...
    { ...
        'AppliedVoltage_V', ...
        'SteadyStateVelocity_rad_s', ...
        'SteadyStateCurrent_A' ...
    } ...
);


%% Part E - Command Window output
%% This can be alter just formatting
fprintf('\n');
fprintf('============================================================\n');
fprintf('                DC MOTOR SIMULATION RESULTS\n');
fprintf('============================================================\n\n');

fprintf('DC Motor Transfer Function:\n\n');

fprintf( ...
    '                         %.6g\n', ...
    transfer_function_numerator ...
);

fprintf( ...
    'G(s) = --------------------------------------------------\n' ...
);

fprintf( ...
    '       %.6g s^2 + %.6g s + %.6g\n\n', ...
    second_order_coefficient, ...
    first_order_coefficient, ...
    constant_coefficient ...
);

fprintf( ...
    'Peak armature current: %.3f A\n', ...
    peak_armature_current ...
);

fprintf( ...
    'Time of peak current: %.6f s\n', ...
    peak_current_time ...
);

fprintf( ...
    'Final angular velocity: %.3f rad/s\n', ...
    final_angular_velocity ...
);

fprintf( ...
    'Final armature current: %.3f A\n', ...
    final_armature_current ...
);

fprintf( ...
    'Steady-state angular velocity: %.2f rad/s\n', ...
    steady_state_angular_velocity ...
);

fprintf( ...
    'Steady-state armature current: %.2f A\n', ...
    steady_state_armature_current ...
);

fprintf( ...
    'Maximum ODE/transfer-function error: %.6f rad/s\n\n', ...
    maximum_model_error ...
);

fprintf('Voltage Comparison:\n\n');

disp(voltage_results_table);

fprintf('============================================================\n');


%% Part E - Formatted data for summary figure
%% This just make shit look nicer, make it easier on the eyes it can be removed 

formatted_result_values = {
    sprintf('%.2f', applied_voltage);
    sprintf('%.3f', peak_armature_current);
    sprintf('%.6f', peak_current_time);
    sprintf('%.3f', final_angular_velocity);
    sprintf('%.3f', final_armature_current);
    sprintf('%.3f', steady_state_angular_velocity);
    sprintf('%.3f', steady_state_armature_current);
    sprintf('%.6f', maximum_model_error)
};

summary_display_data = [
    result_names, ...
    formatted_result_values, ...
    result_units
];

voltage_display_data = cell( ...
    number_of_voltages, ...
    3 ...
);

for voltage_index = 1:number_of_voltages

    voltage_display_data{voltage_index, 1} = ...
        sprintf('%.1f', applied_voltages(voltage_index));

    voltage_display_data{voltage_index, 2} = ...
        sprintf('%.3f', steady_state_velocities(voltage_index));

    voltage_display_data{voltage_index, 3} = ...
        sprintf('%.3f', steady_state_currents(voltage_index));
end


%% Figure 7 - Results summary
%% This just make shit look nicer one the eyes it can be removed 

results_figure = figure( ...
    'Name', ...
    'DC Motor Results Summary', ...
    'NumberTitle', ...
    'off' ...
);

annotation( ...
    results_figure, ...
    'textbox', ...
    [0.05, 0.92, 0.90, 0.06], ...
    'String', ...
    'DC Motor Simulation Results', ...
    'HorizontalAlignment', ...
    'center', ...
    'FontWeight', ...
    'bold', ...
    'FontSize', ...
    14, ...
    'EdgeColor', ...
    'none' ...
);

annotation( ...
    results_figure, ...
    'textbox', ...
    [0.05, 0.84, 0.90, 0.05], ...
    'String', ...
    '10 V Simulation Summary', ...
    'HorizontalAlignment', ...
    'center', ...
    'FontWeight', ...
    'bold', ...
    'FontSize', ...
    11, ...
    'EdgeColor', ...
    'none' ...
);

summary_table_ui = uitable( ...
    results_figure, ...
    'Data', ...
    summary_display_data, ...
    'ColumnName', ...
    {'Quantity', 'Value', 'Unit'}, ...
    'Units', ...
    'normalized', ...
    'Position', ...
    [0.05, 0.42, 0.90, 0.40] ...
);

summary_table_ui.ColumnWidth = {
    250, ...
    130, ...
    100
};

annotation( ...
    results_figure, ...
    'textbox', ...
    [0.05, 0.33, 0.90, 0.05], ...
    'String', ...
    'Applied Voltage Comparison', ...
    'HorizontalAlignment', ...
    'center', ...
    'FontWeight', ...
    'bold', ...
    'FontSize', ...
    11, ...
    'EdgeColor', ...
    'none' ...
);

voltage_table_ui = uitable( ...
    results_figure, ...
    'Data', ...
    voltage_display_data, ...
    'ColumnName', ...
    { ...
        'Voltage (V)', ...
        'Steady-State Velocity (rad/s)', ...
        'Steady-State Current (A)' ...
    }, ...
    'Units', ...
    'normalized', ...
    'Position', ...
    [0.05, 0.07, 0.90, 0.23] ...
);

voltage_table_ui.ColumnWidth = {
    120, ...
    220, ...
    190
};