function [time, armature_current, angular_velocity] = ...
        simulate_dc_motor( ...
        simulation_time, ...
        initial_state, ...
        applied_voltage, ...
        motor_parameters)
%SIMULATE_DC_MOTOR Simulate a DC motor using ode45.
%
% Inputs:
%   simulation_time  - Simulation time vector [s]
%   initial_state    - Initial current and velocity
%   applied_voltage  - Applied armature voltage [V]
%   motor_parameters - Structure containing motor parameters
%
% Outputs:
%   time             - Simulation time [s]
%   armature_current - Armature current [A]
%   angular_velocity - Angular velocity [rad/s]

    motor_ode = @(time_value, state) dc_motor_ode( ...
        time_value, ...
        state, ...
        applied_voltage, ...
        motor_parameters ...
    );

    [time, motor_state] = ode45( ...
        motor_ode, ...
        simulation_time, ...
        initial_state ...
    );

    armature_current = motor_state(:, 1);
    angular_velocity = motor_state(:, 2);
end